openapi: 3.0.1
info:
  title: Platform API
  description: An API designed to enable data context management via API calls.
  contact:
    name: Jānis Radiņš
    email: jr@janisradins.com
  version: 1.0.0
tags:
  - name: Data push
paths:
  /{contexId}/individual-message/:
    post:
      summary: Post message to individual connection (or connections), identified by connection id provided upon initialization.
      tags:
        - Data push
      parameters:
        - in: path
          name: contexId
          required: true
          schema:
            type:
              string
      requestBody:
        required: true
        description: Data to be transfered to one or multiple connections.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IndividualMessage"
      responses:
        200:
          $ref: "#/components/responses/MessageDeliveryReport"
        400:
          $ref: "#/components/responses/BadRequestData"
        401:
          $ref: "#/components/responses/Unauthorized"
        405:
          $ref: "#/components/responses/ActionProhibited"
        413:
          $ref: "#/components/responses/PayloadTooLarge"
      security:
        - ApiAuthKey: []
  /{contexId}/channel-message/:
    post:
      summary: Post message to data channel (or channels).
      tags:
        - Data push
      parameters:
        - in: path
          name: contexId
          required: true
          schema:
            type:
              string
      requestBody:
        description: Message data object to be delivered to recipients.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChannelMessage"
      responses:
        200:
          $ref: "#/components/responses/MessageDeliveryReport"
        400:
          $ref: "#/components/responses/BadRequestData"
        401:
          $ref: "#/components/responses/Unauthorized"
        405:
          $ref: "#/components/responses/ActionProhibited"
        413:
          $ref: "#/components/responses/PayloadTooLarge"
      security:
        - ApiAuthKey: []
  /{contexId}/multi-channel-message/:
    post:
      summary: Post list of messages to data channels.
      tags:
        - Data push
      parameters:
        - in: path
          name: contexId
          required: true
          schema:
            type:
              string
      requestBody:
        description: List of message data objects to be delivered to recipients.
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/ChannelMessage"
      responses:
        200:
          $ref: "#/components/responses/MessageDeliveryReport"
        400:
          $ref: "#/components/responses/BadRequestData"
        401:
          $ref: "#/components/responses/Unauthorized"
        405:
          $ref: "#/components/responses/ActionProhibited"
        413:
          $ref: "#/components/responses/PayloadTooLarge"
      security:
        - ApiAuthKey: []
components:
  schemas:
    ChannelMessage:
      description: Message data format to be delivered to data cahnnel.
      type: object
      properties:
        channels:
          description: List of data channel names to which message should be delivered.
          type: array
          items:
            type: string
        payload:
          type: string
      required:
        - channel
        - payload
    IndividualMessage:
      description: Message data format to be delivered to indiviual connection.
      type: object
      properties:
        connectionIds:
          type: array
          items:
            type: string
        payload:
          type: string
      required:
        - connectionIds
        - payload
  responses:
    MessageDeliveryReport:
      description: Message delivery report.
      content:
        application/json:
          schema:
            type: object
            properties:
              recipients:
                description: Number of recipients for whom message was sent.
                type: number
            required:
              - recipients
    Unauthorized:
      description: API key is missing, invalid or data context is disabled.
      headers:
        WWW_Authenticate:
          schema:
            type: string
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
            required:
              - error
    ActionProhibited:
      description: Action is not allowed
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
            required:
              - error
    BadRequestData:
      description: Malformed request data.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
              name:
                type: string
                description: Name of a data field that produced error.
            required:
              - error
    PayloadTooLarge:
      description: Paylaod exceed limit.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
            required:
              - error

  securitySchemes:
    ApiAuthKey:
      type: apiKey
      in: header
      name: X-API-KEY
