openapi: 3.0.1
info:
  title: Platform API
  description: |
    An API designed to allow execution of actions within operator data scope via external calls.
  contact:
    name: Jānis Radiņš
    email: jr@janisradins.com
  version: 1.0.0
servers:
  - url: https://localhost:8001/api/platform/
    description: Development server
# schemes:
#   - https
tags:
  - name: Publishing
    description: Api to publish messages vai exteral calls
  - name: Connection
    description: An Api provided to allow operator interact with connections of its context.
  - name: Message cache
    description: Data channel message cache management Api.
paths:
  /individual-message/:
    post:
      summary: Post message to individual connection (or connections), identified by connection external id provided upon initialization.
      tags:
        - Publishing
      requestBody:
        required: true
        description: Data to be transfered to one or multiple connections.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IndividualMessage"
      responses:
        200:
          $ref: "#/components/responses/MessageDeliveryReport"
        400:
          $ref: "#/components/responses/BadRequestData"
        401:
          $ref: "#/components/responses/Unauthorized"
        403:
          $ref: "#/components/responses/ActionProhibited"
        413:
          $ref: "#/components/responses/PayloadTooLarge"
        415:
          $ref: "#/components/responses/UnsupportedMediaType"
        429:
          $ref: "#/components/responses/TooManyRequests"
      security:
        - ApiAuthKey: []
  /channel-message/:
    post:
      summary: Post single message to data channel (or channels).
      tags:
        - Publishing
      requestBody:
        description: Message data object to be delivered to recipients.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChannelMessage"
      responses:
        200:
          $ref: "#/components/responses/MessageDeliveryReport"
        400:
          $ref: "#/components/responses/BadRequestData"
        401:
          $ref: "#/components/responses/Unauthorized"
        403:
          $ref: "#/components/responses/ActionProhibited"
        413:
          $ref: "#/components/responses/PayloadTooLarge"
        415:
          $ref: "#/components/responses/UnsupportedMediaType"
        429:
          $ref: "#/components/responses/TooManyRequests"
      security:
        - ApiAuthKey: []
  /multi-channel-message/:
    post:
      summary: Post list of messages to data channels.
      tags:
        - Publishing
      requestBody:
        description: List of message data objects to be delivered to recipients.
        required: true
        content:
          application/json:
            schema:
              type: array
              minItems: 1
              maxItems: 50
              items:
                $ref: "#/components/schemas/ChannelMessage"
      responses:
        200:
          $ref: "#/components/responses/MessageDeliveryReport"
        400:
          $ref: "#/components/responses/BadRequestData"
        401:
          $ref: "#/components/responses/Unauthorized"
        403:
          $ref: "#/components/responses/ActionProhibited"
        413:
          $ref: "#/components/responses/PayloadTooLarge"
        415:
          $ref: "#/components/responses/UnsupportedMediaType"
        429:
          $ref: "#/components/responses/TooManyRequests"
      security:
        - ApiAuthKey: []

  /connection/{connectionId}:
    parameters:
      - $ref:  "#/components/parameters/connectionId"
    get:
      summary: Retrieve connection status and runtime statistics
      tags:
        - Connection
      responses:
        200:
          description: Connection status data.
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  connectionId:
                    type: string
                    description: Internal id of a connection assigned by Platform.
                  externalId:
                    type: string
                    description: Internal id of a connection assigned by Operator during handshake.
                  uptime:
                    type: number
                    description: Seconds since connection is established.
                  bytesSent:
                    type: number
                    description: Bytes sent from server to client.
                  bytesReceived:
                    type: number
                    description: Bytes recevied from client connection.
                required:
                  - connectionId
                  - uptime
                  - bytesSent
                  - bytesReceived
        401:
          $ref: "#/components/responses/Unauthorized"
        404:
          description: Connection could not be found.
        403:
          $ref: "#/components/responses/ActionProhibited"
        429:
          $ref: "#/components/responses/TooManyRequests"
      security:
        - ApiAuthKey: []
    delete:
      summary: Drop client connection
      tags:
        - Connection
      responses:
        200:
          description: Connection found and dropped.
        401:
          $ref: "#/components/responses/Unauthorized"
        404:
          description: Connection could not be found.
        403:
          $ref: "#/components/responses/ActionProhibited"
        429:
          $ref: "#/components/responses/TooManyRequests"
      security:
        - ApiAuthKey: []

  /message-cache/{channel}:
    parameters:
      - $ref: "#/components/parameters/channel"
    get:
      summary: Retrieve message cache stats of a channel.
      tags:
        - Message cache
      responses:
        200:
          description: Channel message cache stats.
          content:
            application/json:
              schema:
                type: object
                properties:
                  length:
                    type: integer
                    description: Number of messages in cache.
                  sizeInBytes:
                    type: integer
                    description: Bytes taken by all messages in cache.
                required:
                  - length
                  - sizeInBytes
        401:
          $ref: "#/components/responses/Unauthorized"
        404:
          description: Required channel do not have message cache enabled.
        403:
          $ref: "#/components/responses/ActionProhibited"
        429:
          $ref: "#/components/responses/TooManyRequests"
      security:
        - ApiAuthKey: []
    delete:
      summary: Clear data channel message cache.
      tags:
        - Message cache
      responses:
        200:
          description: Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: integer
                    description: Number of messages removed from cache due to this call.
        401:
          $ref: "#/components/responses/Unauthorized"
        403:
          $ref: "#/components/responses/ActionProhibited"
        404:
          description: Required channel do not have message cache enabled.
        429:
          $ref: "#/components/responses/TooManyRequests"
      security:
        - ApiAuthKey: []
components:
  schemas:
    ChannelMessage:
      description: Message data format to be delivered to data cahnnel.
      additionalProperties: false
      type: object
      properties:
        channels:
          description: List of data channel names to which message should be delivered.
          type: array
          minItems: 1
          maxItems: 100 #TODO: This maximums is not based on calculation nor it's respected in implementation
          items:
            $ref: "#/components/schemas/ChannelId"
        payload:
          type: string
      required:
        - channels
        - payload
    IndividualMessage:
      description: Message data format to be delivered to indiviual connection.
      type: object
      additionalProperties: false
      properties:
        connectionIds:
          type: array
          minItems: 1
          maxItems: 100 #TODO: This maximums is not based on calculation nor it's respected in implementation
          items:
            type: string

        payload:
          type: string
      required:
        - connectionIds
        - payload
    ChannelId:
      type: string
      pattern: "[a-zA-Z\\d]+" # TODO: ........
      minLength: 2
      maxLength: 50
    ConnectionId:
      description: Client connection internal id
      type: string
      pattern: "[a-zA-Z0-9&%+=]+" # TODO: ........
      minLength: 24
      maxLength: 24
  parameters:
    connectionId:
      name: connectionId
      in: path
      required: true
      schema:
        $ref:  "#/components/schemas/ConnectionId"
      description: Client connection internal id
    channel:
      name: channel
      in: path
      required: true
      schema:
        type: string
        pattern: "^[a-zA-Z\\d.-]+$"
        maxLength: 50
      description: Data channel id
  responses:
    MessageDeliveryReport:
      description: Message delivery report.
      content:
        application/json:
          schema:
            type: object
            properties:
              recipients:
                description: Number of recipients for whom message was sent.
                type: integer
                format: int32
            required:
              - recipients
    Unauthorized:
      description: API key is missing, invalid or data context is disabled.
      headers:
        WWW_Authenticate:
          schema:
            type: string
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
            required:
              - error
    ActionProhibited:
      description: Action is not allowed
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
            required:
              - error
    BadRequestData:
      description: Malformed request data.
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              error:
                type: string
              field:
                type: string
                description: Name of a data field that produced error.
            required:
              - error
    PayloadTooLarge:
      description: Paylaod exceed limit.
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              error:
                type: string
            required:
              - error
    TooManyRequests:
      description: Too many incoming requests.
      headers:
        Retry-After:
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 600
          description: Seconds to await before next request is allowed.
      content: 
        text/plain:
           schema:
            type: string
            enum:
              - Too many incoming requests
    UnsupportedMediaType:
      description: Unsupported media type
      content: 
         text/plain:
           schema:
            type: string
            enum:
              - Unsupported media type
  securitySchemes:
    ApiAuthKey:
      description: Api access key issued by Platform.
      type: apiKey
      in: header
      name: X-API-KEY
