openapi: 3.0.1
info:
  title: Validation API
  description: Data validation API implemented by Operator in order to provide validation for data context actions.
  contact:
    name: Jānis Radiņš
    email: jr@janisradins.com
  version: 1.0.0
tags:
  - name: Validation
paths:
  /validate-connection/:
    post:
      summary: Validate new connection before it's added to connection pool.
      tags:
        - Validation
      requestBody:
        required: true
        description: All the data known about connection prior to handshake finish.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConnectionData"
      responses:
        200:
          $ref: "#/components/responses/ValidationSuccess"
        405:
          $ref: "#/components/responses/ActionProhibited"

      security:
        - ApiAuthKey: []

components:
  schemas:
    ConnectionData:
      description: Connection data - evenrything that is known about connection before handshake is actually finished.
      type: object
      properties:
        connectionId:
          type: string
          description: Internal identifier of a connection.
        remoteAddress:
          type: string
          description: Remote address of a connection.
        forwardedFor:
          type: array
          description: List of hosts described in x-forwarded-for header to identify originating IP address of a client connection.
          items:
            type: string
        ipAddress:
          type: string
          description: IP address of a connection - either remote address or value from forwardedFor, if it's present.
        host:
          type: string
          description: Host name client is connected to.
        url:
          type: string
          description: Exact client connection URL
        origin:
          type: string
          description: Origin of connection declared via headers.
      required:
        - connectionId
        - remoteAddress
        - ipAddress
        - host
        - url
  responses:
    ValidationSuccess:
      description: Success response to new connection validation request indicating that connection handshake can be carried on.
      content:
        application/json:
          schema:
            type: object
            properties:
              externalId:
                description: External id to be assigned to connection so it can be referenced via Operator to Platform API calls.
                type: string
    Unauthorized:
      description: API key is missing, invalid or data context is disabled.
      headers:
        WWW_Authenticate:
          schema:
            type: string
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
            required:
              - error
    ActionProhibited:
      description: Action is not allowed
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string

  securitySchemes:
    ApiAuthKey:
      type: apiKey
      in: header
      name: X-API-KEY
